# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dateTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(864, 596)
        MainWindow.setMaximumSize(QtCore.QSize(864, 596))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(864, 596))
        self.centralwidget.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #304352, stop:1 #d7d2cc);\n"
            "border-radius:5px;")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setGeometry(QtCore.QRect(0, 55, 861, 90))
        self.frame_1.setStyleSheet("QFrame{\n"
                                   "background-color: none;\n"
                                   "border-top:1px solid black;\n"
                                   "}\n"
                                   "\n"
                                   "QFrame:hover{\n"
                                   "background-color: rgb(163, 161, 158);\n"
                                   "}")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.title_frame_1 = QtWidgets.QLabel(self.frame_1)
        self.title_frame_1.setGeometry(QtCore.QRect(20, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.title_frame_1.setFont(font)
        self.title_frame_1.setStyleSheet("background-color: none;\n"
                                         "border-top:none;")
        self.title_frame_1.setObjectName("title_frame_1")
        self.Describtion_frame_1 = QtWidgets.QLabel(self.frame_1)
        self.Describtion_frame_1.setGeometry(QtCore.QRect(20, 50, 621, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Describtion_frame_1.setFont(font)
        self.Describtion_frame_1.setStyleSheet("background-color: none;\n"
                                               "border-top:none;")
        self.Describtion_frame_1.setObjectName("Describtion_frame_1")
        self.inputtime_frame_1 = QtWidgets.QLabel(self.frame_1)
        self.inputtime_frame_1.setGeometry(QtCore.QRect(220, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.inputtime_frame_1.setFont(font)
        self.inputtime_frame_1.setStyleSheet("background-color: none;\n"
                                             "border-top:none;")
        self.inputtime_frame_1.setAlignment(QtCore.Qt.AlignCenter)
        self.inputtime_frame_1.setObjectName("inputtime_frame_1")
        self.retime_frame_1 = QtWidgets.QLabel(self.frame_1)
        self.retime_frame_1.setGeometry(QtCore.QRect(500, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.retime_frame_1.setFont(font)
        self.retime_frame_1.setStyleSheet("background-color: none;\n"
                                          "border-top:none;")
        self.retime_frame_1.setAlignment(QtCore.Qt.AlignCenter)
        self.retime_frame_1.setObjectName("retime_frame_1")
        self.delete_btn_1 = QtWidgets.QPushButton(self.frame_1)
        self.delete_btn_1.setGeometry(QtCore.QRect(800, 23, 51, 51))
        self.delete_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_btn_1.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(115, 115, 115);\n"
                                        "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(85, 85, 85);\n"
                                        "border-radius:5px;\n"
                                        "}")
        self.delete_btn_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("photo/outline_delete_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_btn_1.setIcon(icon)
        self.delete_btn_1.setIconSize(QtCore.QSize(32, 32))
        self.delete_btn_1.setObjectName("delete_btn_1")
        self.active_btn_1 = QtWidgets.QPushButton(self.frame_1)
        self.active_btn_1.setGeometry(QtCore.QRect(680, 23, 51, 51))
        self.active_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.active_btn_1.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(115, 115, 115);\n"
                                        "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(85, 85, 85);\n"
                                        "border-radius:5px;\n"
                                        "}")
        self.active_btn_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("photo/outline_alarm_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.active_btn_1.setIcon(icon1)
        self.active_btn_1.setIconSize(QtCore.QSize(32, 32))
        self.active_btn_1.setObjectName("active_btn_1")
        self.edit_btn_1 = QtWidgets.QPushButton(self.frame_1)
        self.edit_btn_1.setGeometry(QtCore.QRect(740, 23, 51, 51))
        self.edit_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit_btn_1.setStyleSheet("QPushButton{\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(115, 115, 115);\n"
                                      "border-radius:10px;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(85, 85, 85);\n"
                                      "border-radius:5px;\n"
                                      "}")
        self.edit_btn_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("photo/outline_edit_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_btn_1.setIcon(icon2)
        self.edit_btn_1.setIconSize(QtCore.QSize(32, 32))
        self.edit_btn_1.setObjectName("edit_btn_1")
        self.date_frame_1 = QtWidgets.QLabel(self.frame_1)
        self.date_frame_1.setGeometry(QtCore.QRect(370, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.date_frame_1.setFont(font)
        self.date_frame_1.setStyleSheet("background-color: none;\n"
                                        "border-top:none;")
        self.date_frame_1.setAlignment(QtCore.Qt.AlignCenter)
        self.date_frame_1.setObjectName("date_frame_1")
        self.day_re_frame_1 = QtWidgets.QLabel(self.frame_1)
        self.day_re_frame_1.setGeometry(QtCore.QRect(626, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.day_re_frame_1.setFont(font)
        self.day_re_frame_1.setStyleSheet("background-color: none;\n"
                                          "border-top:none;")
        self.day_re_frame_1.setAlignment(QtCore.Qt.AlignCenter)
        self.day_re_frame_1.setObjectName("day_re_frame_1")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 145, 861, 90))
        self.frame_2.setStyleSheet("QFrame{\n"
                                   "background-color: none;\n"
                                   "border-top:1px solid black;\n"
                                   "}\n"
                                   "\n"
                                   "QFrame:hover{\n"
                                   "background-color: rgb(163, 161, 158);\n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.title_frame_2 = QtWidgets.QLabel(self.frame_2)
        self.title_frame_2.setGeometry(QtCore.QRect(20, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.title_frame_2.setFont(font)
        self.title_frame_2.setStyleSheet("background-color: none;\n"
                                         "border-top:none;")
        self.title_frame_2.setObjectName("title_frame_2")
        self.Describtion_frame_2 = QtWidgets.QLabel(self.frame_2)
        self.Describtion_frame_2.setGeometry(QtCore.QRect(20, 50, 621, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.Describtion_frame_2.setFont(font)
        self.Describtion_frame_2.setStyleSheet("background-color: none;\n"
                                               "border-top:none;")
        self.Describtion_frame_2.setObjectName("Describtion_frame_2")
        self.inputtime_frame_2 = QtWidgets.QLabel(self.frame_2)
        self.inputtime_frame_2.setGeometry(QtCore.QRect(220, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.inputtime_frame_2.setFont(font)
        self.inputtime_frame_2.setStyleSheet("background-color: none;\n"
                                             "border-top:none;")
        self.inputtime_frame_2.setAlignment(QtCore.Qt.AlignCenter)
        self.inputtime_frame_2.setObjectName("inputtime_frame_2")
        self.retime_frame_2 = QtWidgets.QLabel(self.frame_2)
        self.retime_frame_2.setGeometry(QtCore.QRect(500, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.retime_frame_2.setFont(font)
        self.retime_frame_2.setStyleSheet("background-color: none;\n"
                                          "border-top:none;")
        self.retime_frame_2.setAlignment(QtCore.Qt.AlignCenter)
        self.retime_frame_2.setObjectName("retime_frame_2")
        self.edit_btn_2 = QtWidgets.QPushButton(self.frame_2)
        self.edit_btn_2.setGeometry(QtCore.QRect(740, 23, 51, 51))
        self.edit_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit_btn_2.setStyleSheet("QPushButton{\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(115, 115, 115);\n"
                                      "border-radius:10px;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(85, 85, 85);\n"
                                      "border-radius:5px;\n"
                                      "}")
        self.edit_btn_2.setText("")
        self.edit_btn_2.setIcon(icon2)
        self.edit_btn_2.setIconSize(QtCore.QSize(32, 32))
        self.edit_btn_2.setObjectName("edit_btn_2")
        self.delete_btn_2 = QtWidgets.QPushButton(self.frame_2)
        self.delete_btn_2.setGeometry(QtCore.QRect(800, 23, 51, 51))
        self.delete_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_btn_2.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(115, 115, 115);\n"
                                        "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(85, 85, 85);\n"
                                        "border-radius:5px;\n"
                                        "}")
        self.delete_btn_2.setText("")
        self.delete_btn_2.setIcon(icon)
        self.delete_btn_2.setIconSize(QtCore.QSize(32, 32))
        self.delete_btn_2.setObjectName("delete_btn_2")
        self.active_btn_2 = QtWidgets.QPushButton(self.frame_2)
        self.active_btn_2.setGeometry(QtCore.QRect(680, 23, 51, 51))
        self.active_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.active_btn_2.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(115, 115, 115);\n"
                                        "    \n"
                                        "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(85, 85, 85);\n"
                                        "border-radius:5px;\n"
                                        "}")
        self.active_btn_2.setText("")
        self.active_btn_2.setIcon(icon1)
        self.active_btn_2.setIconSize(QtCore.QSize(32, 32))
        self.active_btn_2.setObjectName("active_btn_2")
        self.date_frame_2 = QtWidgets.QLabel(self.frame_2)
        self.date_frame_2.setGeometry(QtCore.QRect(370, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.date_frame_2.setFont(font)
        self.date_frame_2.setStyleSheet("background-color: none;\n"
                                        "border-top:none;")
        self.date_frame_2.setAlignment(QtCore.Qt.AlignCenter)
        self.date_frame_2.setObjectName("date_frame_2")
        self.day_re_frame_2 = QtWidgets.QLabel(self.frame_2)
        self.day_re_frame_2.setGeometry(QtCore.QRect(626, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.day_re_frame_2.setFont(font)
        self.day_re_frame_2.setStyleSheet("background-color: none;\n"
                                          "border-top:none;")
        self.day_re_frame_2.setAlignment(QtCore.Qt.AlignCenter)
        self.day_re_frame_2.setObjectName("day_re_frame_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 235, 861, 90))
        self.frame_3.setStyleSheet("QFrame{\n"
                                   "background-color: none;\n"
                                   "border-top:1px solid black;\n"
                                   "}\n"
                                   "\n"
                                   "QFrame:hover{\n"
                                   "background-color: rgb(163, 161, 158);\n"
                                   "}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.title_frame_3 = QtWidgets.QLabel(self.frame_3)
        self.title_frame_3.setGeometry(QtCore.QRect(20, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.title_frame_3.setFont(font)
        self.title_frame_3.setStyleSheet("background-color: none;\n"
                                         "border-top:none;")
        self.title_frame_3.setObjectName("title_frame_3")
        self.Describtion_frame_3 = QtWidgets.QLabel(self.frame_3)
        self.Describtion_frame_3.setGeometry(QtCore.QRect(20, 50, 621, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.Describtion_frame_3.setFont(font)
        self.Describtion_frame_3.setStyleSheet("background-color: none;\n"
                                               "border-top:none;")
        self.Describtion_frame_3.setObjectName("Describtion_frame_3")
        self.inputtime_frame_3 = QtWidgets.QLabel(self.frame_3)
        self.inputtime_frame_3.setGeometry(QtCore.QRect(220, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.inputtime_frame_3.setFont(font)
        self.inputtime_frame_3.setStyleSheet("background-color: none;\n"
                                             "border-top:none;")
        self.inputtime_frame_3.setAlignment(QtCore.Qt.AlignCenter)
        self.inputtime_frame_3.setObjectName("inputtime_frame_3")
        self.retime_frame_3 = QtWidgets.QLabel(self.frame_3)
        self.retime_frame_3.setGeometry(QtCore.QRect(500, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.retime_frame_3.setFont(font)
        self.retime_frame_3.setStyleSheet("background-color: none;\n"
                                          "border-top:none;")
        self.retime_frame_3.setAlignment(QtCore.Qt.AlignCenter)
        self.retime_frame_3.setObjectName("retime_frame_3")
        self.active_btn_3 = QtWidgets.QPushButton(self.frame_3)
        self.active_btn_3.setGeometry(QtCore.QRect(680, 23, 51, 51))
        self.active_btn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.active_btn_3.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(115, 115, 115);\n"
                                        "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(85, 85, 85);\n"
                                        "border-radius:5px;\n"
                                        "}")
        self.active_btn_3.setText("")
        self.active_btn_3.setIcon(icon1)
        self.active_btn_3.setIconSize(QtCore.QSize(32, 32))
        self.active_btn_3.setObjectName("active_btn_3")
        self.edit_btn_3 = QtWidgets.QPushButton(self.frame_3)
        self.edit_btn_3.setGeometry(QtCore.QRect(740, 23, 51, 51))
        self.edit_btn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit_btn_3.setStyleSheet("QPushButton{\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(115, 115, 115);\n"
                                      "border-radius:10px;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(85, 85, 85);\n"
                                      "border-radius:5px;\n"
                                      "}")
        self.edit_btn_3.setText("")
        self.edit_btn_3.setIcon(icon2)
        self.edit_btn_3.setIconSize(QtCore.QSize(32, 32))
        self.edit_btn_3.setObjectName("edit_btn_3")
        self.delete_btn_3 = QtWidgets.QPushButton(self.frame_3)
        self.delete_btn_3.setGeometry(QtCore.QRect(800, 23, 51, 51))
        self.delete_btn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_btn_3.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(115, 115, 115);\n"
                                        "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(85, 85, 85);\n"
                                        "border-radius:5px;\n"
                                        "}")
        self.delete_btn_3.setText("")
        self.delete_btn_3.setIcon(icon)
        self.delete_btn_3.setIconSize(QtCore.QSize(32, 32))
        self.delete_btn_3.setObjectName("delete_btn_3")
        self.date_frame_3 = QtWidgets.QLabel(self.frame_3)
        self.date_frame_3.setGeometry(QtCore.QRect(370, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.date_frame_3.setFont(font)
        self.date_frame_3.setStyleSheet("background-color: none;\n"
                                        "border-top:none;")
        self.date_frame_3.setAlignment(QtCore.Qt.AlignCenter)
        self.date_frame_3.setObjectName("date_frame_3")
        self.day_re_frame_3 = QtWidgets.QLabel(self.frame_3)
        self.day_re_frame_3.setGeometry(QtCore.QRect(626, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.day_re_frame_3.setFont(font)
        self.day_re_frame_3.setStyleSheet("background-color: none;\n"
                                          "border-top:none;")
        self.day_re_frame_3.setAlignment(QtCore.Qt.AlignCenter)
        self.day_re_frame_3.setObjectName("day_re_frame_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(1, 325, 861, 90))
        self.frame_4.setStyleSheet("QFrame{\n"
                                   "background-color: none;\n"
                                   "border-top:1px solid black;\n"
                                   "}\n"
                                   "\n"
                                   "QFrame:hover{\n"
                                   "background-color: rgb(163, 161, 158);\n"
                                   "}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.title_frame_4 = QtWidgets.QLabel(self.frame_4)
        self.title_frame_4.setGeometry(QtCore.QRect(20, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.title_frame_4.setFont(font)
        self.title_frame_4.setStyleSheet("background-color: none;\n"
                                         "border-top:none;")
        self.title_frame_4.setObjectName("title_frame_4")
        self.Describtion_frame_4 = QtWidgets.QLabel(self.frame_4)
        self.Describtion_frame_4.setGeometry(QtCore.QRect(20, 50, 621, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.Describtion_frame_4.setFont(font)
        self.Describtion_frame_4.setStyleSheet("background-color: none;\n"
                                               "border-top:none;")
        self.Describtion_frame_4.setObjectName("Describtion_frame_4")
        self.inputtime_frame_4 = QtWidgets.QLabel(self.frame_4)
        self.inputtime_frame_4.setGeometry(QtCore.QRect(220, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.inputtime_frame_4.setFont(font)
        self.inputtime_frame_4.setStyleSheet("background-color: none;\n"
                                             "border-top:none;")
        self.inputtime_frame_4.setAlignment(QtCore.Qt.AlignCenter)
        self.inputtime_frame_4.setObjectName("inputtime_frame_4")
        self.retime_frame_4 = QtWidgets.QLabel(self.frame_4)
        self.retime_frame_4.setGeometry(QtCore.QRect(500, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.retime_frame_4.setFont(font)
        self.retime_frame_4.setStyleSheet("background-color: none;\n"
                                          "border-top:none;")
        self.retime_frame_4.setAlignment(QtCore.Qt.AlignCenter)
        self.retime_frame_4.setObjectName("retime_frame_4")
        self.active_btn_4 = QtWidgets.QPushButton(self.frame_4)
        self.active_btn_4.setGeometry(QtCore.QRect(680, 23, 51, 51))
        self.active_btn_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.active_btn_4.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(115, 115, 115);\n"
                                        "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(85, 85, 85);\n"
                                        "border-radius:5px;\n"
                                        "}")
        self.active_btn_4.setText("")
        self.active_btn_4.setIcon(icon1)
        self.active_btn_4.setIconSize(QtCore.QSize(32, 32))
        self.active_btn_4.setObjectName("active_btn_4")
        self.edit_btn_4 = QtWidgets.QPushButton(self.frame_4)
        self.edit_btn_4.setGeometry(QtCore.QRect(740, 23, 51, 51))
        self.edit_btn_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit_btn_4.setStyleSheet("QPushButton{\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(115, 115, 115);\n"
                                      "border-radius:10px;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(85, 85, 85);\n"
                                      "border-radius:5px;\n"
                                      "}")
        self.edit_btn_4.setText("")
        self.edit_btn_4.setIcon(icon2)
        self.edit_btn_4.setIconSize(QtCore.QSize(32, 32))
        self.edit_btn_4.setObjectName("edit_btn_4")
        self.delete_btn_4 = QtWidgets.QPushButton(self.frame_4)
        self.delete_btn_4.setGeometry(QtCore.QRect(800, 23, 51, 51))
        self.delete_btn_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_btn_4.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(115, 115, 115);\n"
                                        "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(85, 85, 85);\n"
                                        "border-radius:5px;\n"
                                        "}")
        self.delete_btn_4.setText("")
        self.delete_btn_4.setIcon(icon)
        self.delete_btn_4.setIconSize(QtCore.QSize(32, 32))
        self.delete_btn_4.setObjectName("delete_btn_4")
        self.date_frame_4 = QtWidgets.QLabel(self.frame_4)
        self.date_frame_4.setGeometry(QtCore.QRect(370, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.date_frame_4.setFont(font)
        self.date_frame_4.setStyleSheet("background-color: none;\n"
                                        "border-top:none;")
        self.date_frame_4.setAlignment(QtCore.Qt.AlignCenter)
        self.date_frame_4.setObjectName("date_frame_4")
        self.day_re_frame_4 = QtWidgets.QLabel(self.frame_4)
        self.day_re_frame_4.setGeometry(QtCore.QRect(626, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.day_re_frame_4.setFont(font)
        self.day_re_frame_4.setStyleSheet("background-color: none;\n"
                                          "border-top:none;")
        self.day_re_frame_4.setAlignment(QtCore.Qt.AlignCenter)
        self.day_re_frame_4.setObjectName("day_re_frame_4")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(0, 415, 861, 90))
        self.frame_5.setToolTip("")
        self.frame_5.setStyleSheet("QFrame{\n"
                                   "background-color: none;\n"
                                   "border-top:1px solid black;\n"
                                   "}\n"
                                   "\n"
                                   "QFrame:hover{\n"
                                   "background-color: rgb(163, 161, 158);\n"
                                   "}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.title_frame_5 = QtWidgets.QLabel(self.frame_5)
        self.title_frame_5.setGeometry(QtCore.QRect(20, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.title_frame_5.setFont(font)
        self.title_frame_5.setStyleSheet("background-color: none;\n"
                                         "border-top:none;")
        self.title_frame_5.setObjectName("title_frame_5")
        self.Describtion_frame_5 = QtWidgets.QLabel(self.frame_5)
        self.Describtion_frame_5.setGeometry(QtCore.QRect(20, 50, 621, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.Describtion_frame_5.setFont(font)
        self.Describtion_frame_5.setStyleSheet("background-color: none;\n"
                                               "border-top:none;")
        self.Describtion_frame_5.setObjectName("Describtion_frame_5")
        self.inputtime_frame_5 = QtWidgets.QLabel(self.frame_5)
        self.inputtime_frame_5.setGeometry(QtCore.QRect(220, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.inputtime_frame_5.setFont(font)
        self.inputtime_frame_5.setStyleSheet("background-color: none;\n"
                                             "border-top:none;")
        self.inputtime_frame_5.setAlignment(QtCore.Qt.AlignCenter)
        self.inputtime_frame_5.setObjectName("inputtime_frame_5")
        self.retime_frame_5 = QtWidgets.QLabel(self.frame_5)
        self.retime_frame_5.setGeometry(QtCore.QRect(500, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.retime_frame_5.setFont(font)
        self.retime_frame_5.setStyleSheet("background-color: none;\n"
                                          "border-top:none;")
        self.retime_frame_5.setAlignment(QtCore.Qt.AlignCenter)
        self.retime_frame_5.setObjectName("retime_frame_5")
        self.active_btn_5 = QtWidgets.QPushButton(self.frame_5)
        self.active_btn_5.setGeometry(QtCore.QRect(680, 23, 51, 51))
        self.active_btn_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.active_btn_5.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(115, 115, 115);\n"
                                        "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(85, 85, 85);\n"
                                        "border-radius:5px;\n"
                                        "}")
        self.active_btn_5.setText("")
        self.active_btn_5.setIcon(icon1)
        self.active_btn_5.setIconSize(QtCore.QSize(32, 32))
        self.active_btn_5.setObjectName("active_btn_5")
        self.edit_btn_5 = QtWidgets.QPushButton(self.frame_5)
        self.edit_btn_5.setGeometry(QtCore.QRect(740, 23, 51, 51))
        self.edit_btn_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit_btn_5.setStyleSheet("QPushButton{\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(115, 115, 115);\n"
                                      "border-radius:10px;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(85, 85, 85);\n"
                                      "border-radius:5px;\n"
                                      "}")
        self.edit_btn_5.setText("")
        self.edit_btn_5.setIcon(icon2)
        self.edit_btn_5.setIconSize(QtCore.QSize(32, 32))
        self.edit_btn_5.setObjectName("edit_btn_5")
        self.delete_btn_5 = QtWidgets.QPushButton(self.frame_5)
        self.delete_btn_5.setGeometry(QtCore.QRect(800, 23, 51, 51))
        self.delete_btn_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_btn_5.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(115, 115, 115);\n"
                                        "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(85, 85, 85);\n"
                                        "border-radius:5px;\n"
                                        "}")
        self.delete_btn_5.setText("")
        self.delete_btn_5.setIcon(icon)
        self.delete_btn_5.setIconSize(QtCore.QSize(32, 32))
        self.delete_btn_5.setObjectName("delete_btn_5")
        self.date_frame_5 = QtWidgets.QLabel(self.frame_5)
        self.date_frame_5.setGeometry(QtCore.QRect(370, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.date_frame_5.setFont(font)
        self.date_frame_5.setStyleSheet("background-color: none;\n"
                                        "border-top:none;")
        self.date_frame_5.setAlignment(QtCore.Qt.AlignCenter)
        self.date_frame_5.setObjectName("date_frame_5")
        self.day_re_frame_5 = QtWidgets.QLabel(self.frame_5)
        self.day_re_frame_5.setGeometry(QtCore.QRect(626, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.day_re_frame_5.setFont(font)
        self.day_re_frame_5.setStyleSheet("background-color: none;\n"
                                          "border-top:none;")
        self.day_re_frame_5.setAlignment(QtCore.Qt.AlignCenter)
        self.day_re_frame_5.setObjectName("day_re_frame_5")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(0, 505, 861, 90))
        self.frame_6.setStyleSheet("QFrame{\n"
                                   "background-color: none;\n"
                                   "border-top:1px solid black;\n"
                                   "}\n"
                                   "\n"
                                   "QFrame:hover{\n"
                                   "background-color: rgb(163, 161, 158);\n"
                                   "}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.title_frame_6 = QtWidgets.QLabel(self.frame_6)
        self.title_frame_6.setGeometry(QtCore.QRect(20, 10, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.title_frame_6.setFont(font)
        self.title_frame_6.setStyleSheet("background-color: none;\n"
                                         "border-top:none;")
        self.title_frame_6.setObjectName("title_frame_6")
        self.Describtion_frame_6 = QtWidgets.QLabel(self.frame_6)
        self.Describtion_frame_6.setGeometry(QtCore.QRect(20, 50, 621, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.Describtion_frame_6.setFont(font)
        self.Describtion_frame_6.setStyleSheet("background-color: none;\n"
                                               "border-top:none;")
        self.Describtion_frame_6.setObjectName("Describtion_frame_6")
        self.inputtime_frame_6 = QtWidgets.QLabel(self.frame_6)
        self.inputtime_frame_6.setGeometry(QtCore.QRect(220, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.inputtime_frame_6.setFont(font)
        self.inputtime_frame_6.setStyleSheet("background-color: none;\n"
                                             "border-top:none;")
        self.inputtime_frame_6.setAlignment(QtCore.Qt.AlignCenter)
        self.inputtime_frame_6.setObjectName("inputtime_frame_6")
        self.retime_frame_6 = QtWidgets.QLabel(self.frame_6)
        self.retime_frame_6.setGeometry(QtCore.QRect(500, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.retime_frame_6.setFont(font)
        self.retime_frame_6.setStyleSheet("background-color: none;\n"
                                          "border-top:none;")
        self.retime_frame_6.setAlignment(QtCore.Qt.AlignCenter)
        self.retime_frame_6.setObjectName("retime_frame_6")
        self.edit_btn_6 = QtWidgets.QPushButton(self.frame_6)
        self.edit_btn_6.setGeometry(QtCore.QRect(740, 23, 51, 51))
        self.edit_btn_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edit_btn_6.setStyleSheet("QPushButton{\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(115, 115, 115);\n"
                                      "border-radius:10px;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(85, 85, 85);\n"
                                      "border-radius:5px;\n"
                                      "}")
        self.edit_btn_6.setText("")
        self.edit_btn_6.setIcon(icon2)
        self.edit_btn_6.setIconSize(QtCore.QSize(32, 32))
        self.edit_btn_6.setObjectName("edit_btn_6")
        self.active_btn_6 = QtWidgets.QPushButton(self.frame_6)
        self.active_btn_6.setGeometry(QtCore.QRect(680, 23, 51, 51))
        self.active_btn_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.active_btn_6.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(115, 115, 115);\n"
                                        "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(85, 85, 85);\n"
                                        "border-radius:5px;\n"
                                        "}")
        self.active_btn_6.setText("")
        self.active_btn_6.setIcon(icon1)
        self.active_btn_6.setIconSize(QtCore.QSize(32, 32))
        self.active_btn_6.setObjectName("active_btn_6")
        self.delete_btn_6 = QtWidgets.QPushButton(self.frame_6)
        self.delete_btn_6.setGeometry(QtCore.QRect(800, 23, 51, 51))
        self.delete_btn_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_btn_6.setStyleSheet("QPushButton{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(115, 115, 115);\n"
                                        "border-radius:10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    background-color: rgb(85, 85, 85);\n"
                                        "border-radius:5px;\n"
                                        "}")
        self.delete_btn_6.setText("")
        self.delete_btn_6.setIcon(icon)
        self.delete_btn_6.setIconSize(QtCore.QSize(32, 32))
        self.delete_btn_6.setObjectName("delete_btn_6")
        self.date_frame_6 = QtWidgets.QLabel(self.frame_6)
        self.date_frame_6.setGeometry(QtCore.QRect(370, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.date_frame_6.setFont(font)
        self.date_frame_6.setStyleSheet("background-color: none;\n"
                                        "border-top:none;")
        self.date_frame_6.setAlignment(QtCore.Qt.AlignCenter)
        self.date_frame_6.setObjectName("date_frame_6")
        self.day_re_frame_6 = QtWidgets.QLabel(self.frame_6)
        self.day_re_frame_6.setGeometry(QtCore.QRect(626, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.day_re_frame_6.setFont(font)
        self.day_re_frame_6.setStyleSheet("background-color: none;\n"
                                          "border-top:none;")
        self.day_re_frame_6.setAlignment(QtCore.Qt.AlignCenter)
        self.day_re_frame_6.setObjectName("day_re_frame_6")
        self.option_frame = QtWidgets.QFrame(self.centralwidget)
        self.option_frame.setGeometry(QtCore.QRect(0, 0, 861, 51))
        self.option_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.option_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.option_frame.setObjectName("option_frame")
        self.minimize = QtWidgets.QPushButton(self.option_frame)
        self.minimize.setGeometry(QtCore.QRect(760, 16, 41, 21))
        self.minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize.setStyleSheet("background-color: rgb(232, 232, 0);\n"
                                    "border-radius:10px;")
        self.minimize.setText("")
        self.minimize.setObjectName("minimize")
        self.exit = QtWidgets.QPushButton(self.option_frame)
        self.exit.setGeometry(QtCore.QRect(810, 16, 41, 21))
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit.setStyleSheet("background-color: rgb(255, 0, 0);\n"
                                "border-radius:10px;")
        self.exit.setText("")
        self.exit.setObjectName("exit")
        self.btn_frame = QtWidgets.QFrame(self.option_frame)
        self.btn_frame.setGeometry(QtCore.QRect(70, 0, 521, 51))
        self.btn_frame.setStyleSheet("background-color: none;\n"
                                     "")
        self.btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_frame.setObjectName("btn_frame")
        self.process_btn = QtWidgets.QPushButton(self.btn_frame)
        self.process_btn.setGeometry(QtCore.QRect(270, 7, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.process_btn.setFont(font)
        self.process_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.process_btn.setToolTip("")
        self.process_btn.setStyleSheet("QPushButton{\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    \n"
                                       "    background-color: rgb(115, 115, 115);\n"
                                       "border-radius:10px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    background-color: rgb(95, 95, 95);\n"
                                       "border-radius:5px;\n"
                                       "}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("photo/outline_power_settings_new_black_24dp.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.process_btn.setIcon(icon3)
        self.process_btn.setIconSize(QtCore.QSize(30, 30))
        self.process_btn.setObjectName("process_btn")
        self.setting_btn = QtWidgets.QPushButton(self.btn_frame)
        self.setting_btn.setGeometry(QtCore.QRect(140, 7, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.setting_btn.setFont(font)
        self.setting_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setting_btn.setToolTip("")
        self.setting_btn.setStyleSheet("QPushButton{\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    \n"
                                       "    background-color: rgb(115, 115, 115);\n"
                                       "border-radius:10px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    background-color: rgb(95, 95, 95);\n"
                                       "border-radius:5px;\n"
                                       "}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("photo/outline_settings_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_btn.setIcon(icon4)
        self.setting_btn.setIconSize(QtCore.QSize(30, 30))
        self.setting_btn.setObjectName("setting_btn")
        self.add_btn = QtWidgets.QPushButton(self.btn_frame)
        self.add_btn.setGeometry(QtCore.QRect(0, 7, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.add_btn.setFont(font)
        self.add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_btn.setToolTip("")
        self.add_btn.setStyleSheet("QPushButton{\n"
                                   "    color: rgb(255, 255, 255);\n"
                                   "    \n"
                                   "    background-color: rgb(115, 115, 115);\n"
                                   "border-radius:10px;\n"
                                   "}\n"
                                   "QPushButton:hover{\n"
                                   "    color: rgb(255, 255, 255);\n"
                                   "    background-color: rgb(95, 95, 95);\n"
                                   "border-radius:5px;\n"
                                   "}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("photo/outline_add_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_btn.setIcon(icon5)
        self.add_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_btn.setObjectName("add_btn")
        self.refresh_btn = QtWidgets.QPushButton(self.btn_frame)
        self.refresh_btn.setGeometry(QtCore.QRect(397, 7, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.refresh_btn.setFont(font)
        self.refresh_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refresh_btn.setStyleSheet("QPushButton{\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    \n"
                                       "    background-color: rgb(115, 115, 115);\n"
                                       "border-radius:10px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    background-color: rgb(95, 95, 95);\n"
                                       "border-radius:5px;\n"
                                       "}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("photo/outline_refresh_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_btn.setIcon(icon6)
        self.refresh_btn.setIconSize(QtCore.QSize(30, 30))
        self.refresh_btn.setObjectName("refresh_btn")
        self.menu_btn = QtWidgets.QPushButton(self.option_frame)
        self.menu_btn.setGeometry(QtCore.QRect(10, 7, 51, 41))
        self.menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_btn.setStyleSheet("QPushButton{\n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "    \n"
                                    "    background-color:none;\n"
                                    "border-radius:10px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "    background-color: rgb(95, 95, 95);\n"
                                    "border-radius:5px;\n"
                                    "}")
        self.menu_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("photo/outline_menu_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_btn.setIcon(icon7)
        self.menu_btn.setIconSize(QtCore.QSize(30, 30))
        self.menu_btn.setObjectName("menu_btn")
        self.currentTime = QtWidgets.QLabel(self.option_frame)
        self.currentTime.setGeometry(QtCore.QRect(610, 0, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.currentTime.setFont(font)
        self.currentTime.setStyleSheet("background-color: none;\n"
                                       "color: rgb(0, 0, 0);")
        self.currentTime.setText("")
        self.currentTime.setAlignment(QtCore.Qt.AlignCenter)
        self.currentTime.setObjectName("currentTime")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.exit.clicked.connect(MainWindow.close)
        self.minimize.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_frame_1.setToolTip(_translate("MainWindow", "Title"))
        self.title_frame_1.setText(_translate("MainWindow", "Title"))
        self.Describtion_frame_1.setToolTip(_translate("MainWindow", "Description"))
        self.Describtion_frame_1.setText(_translate("MainWindow", "Description"))
        self.inputtime_frame_1.setToolTip(_translate("MainWindow", "Input Time"))
        self.inputtime_frame_1.setText(_translate("MainWindow", "Input time"))
        self.retime_frame_1.setToolTip(_translate("MainWindow", "Remaining Time"))
        self.retime_frame_1.setText(_translate("MainWindow", "00:00:00"))
        self.delete_btn_1.setToolTip(_translate("MainWindow", "Delete"))
        self.active_btn_1.setToolTip(_translate("MainWindow", "Active"))
        self.edit_btn_1.setToolTip(_translate("MainWindow", "Edit"))
        self.date_frame_1.setToolTip(_translate("MainWindow", "Date"))
        self.date_frame_1.setText(_translate("MainWindow", "date"))
        self.day_re_frame_1.setText(_translate("MainWindow", "days"))
        self.title_frame_2.setToolTip(_translate("MainWindow", "Title"))
        self.title_frame_2.setText(_translate("MainWindow", "Title"))
        self.Describtion_frame_2.setToolTip(_translate("MainWindow", "Description"))
        self.Describtion_frame_2.setText(_translate("MainWindow", "Description"))
        self.inputtime_frame_2.setToolTip(_translate("MainWindow", "Input Time"))
        self.inputtime_frame_2.setText(_translate("MainWindow", "Input time"))
        self.retime_frame_2.setToolTip(_translate("MainWindow", "Remaining Time"))
        self.retime_frame_2.setText(_translate("MainWindow", "00:00:00"))
        self.edit_btn_2.setToolTip(_translate("MainWindow", "Edit"))
        self.delete_btn_2.setToolTip(_translate("MainWindow", "Delete"))
        self.active_btn_2.setToolTip(_translate("MainWindow", "Active"))
        self.date_frame_2.setToolTip(_translate("MainWindow", "Date"))
        self.date_frame_2.setText(_translate("MainWindow", "date"))
        self.day_re_frame_2.setText(_translate("MainWindow", "days"))
        self.title_frame_3.setToolTip(_translate("MainWindow", "Title"))
        self.title_frame_3.setText(_translate("MainWindow", "Title"))
        self.Describtion_frame_3.setToolTip(_translate("MainWindow", "Description"))
        self.Describtion_frame_3.setText(_translate("MainWindow", "Description"))
        self.inputtime_frame_3.setToolTip(_translate("MainWindow", "Input Time"))
        self.inputtime_frame_3.setText(_translate("MainWindow", "Input time"))
        self.retime_frame_3.setToolTip(_translate("MainWindow", "Remaining Time"))
        self.retime_frame_3.setText(_translate("MainWindow", "00:00:00"))
        self.active_btn_3.setToolTip(_translate("MainWindow", "Active"))
        self.edit_btn_3.setToolTip(_translate("MainWindow", "Edit"))
        self.delete_btn_3.setToolTip(_translate("MainWindow", "Delete"))
        self.date_frame_3.setToolTip(_translate("MainWindow", "Date"))
        self.date_frame_3.setText(_translate("MainWindow", "date"))
        self.day_re_frame_3.setText(_translate("MainWindow", "days"))
        self.title_frame_4.setToolTip(_translate("MainWindow", "Title"))
        self.title_frame_4.setText(_translate("MainWindow", "Title"))
        self.Describtion_frame_4.setToolTip(_translate("MainWindow", "Description"))
        self.Describtion_frame_4.setText(_translate("MainWindow", "Description"))
        self.inputtime_frame_4.setToolTip(_translate("MainWindow", "Input Time"))
        self.inputtime_frame_4.setText(_translate("MainWindow", "Input time"))
        self.retime_frame_4.setToolTip(_translate("MainWindow", "Remaining Time"))
        self.retime_frame_4.setText(_translate("MainWindow", "00:00:00"))
        self.active_btn_4.setToolTip(_translate("MainWindow", "Active"))
        self.edit_btn_4.setToolTip(_translate("MainWindow", "Edit"))
        self.delete_btn_4.setToolTip(_translate("MainWindow", "Delete"))
        self.date_frame_4.setToolTip(_translate("MainWindow", "Date"))
        self.date_frame_4.setText(_translate("MainWindow", "date"))
        self.day_re_frame_4.setText(_translate("MainWindow", "days"))
        self.title_frame_5.setToolTip(_translate("MainWindow", "Title"))
        self.title_frame_5.setText(_translate("MainWindow", "Title"))
        self.Describtion_frame_5.setToolTip(_translate("MainWindow", "Description"))
        self.Describtion_frame_5.setText(_translate("MainWindow", "Description"))
        self.inputtime_frame_5.setToolTip(_translate("MainWindow", "Input Time"))
        self.inputtime_frame_5.setText(_translate("MainWindow", "Input time"))
        self.retime_frame_5.setToolTip(_translate("MainWindow", "Remaining Time"))
        self.retime_frame_5.setText(_translate("MainWindow", "00:00:00"))
        self.active_btn_5.setToolTip(_translate("MainWindow", "Active"))
        self.edit_btn_5.setToolTip(_translate("MainWindow", "Edit"))
        self.delete_btn_5.setToolTip(_translate("MainWindow", "Delete"))
        self.date_frame_5.setToolTip(_translate("MainWindow", "Date"))
        self.date_frame_5.setText(_translate("MainWindow", "date"))
        self.day_re_frame_5.setText(_translate("MainWindow", "days"))
        self.title_frame_6.setToolTip(_translate("MainWindow", "Title"))
        self.title_frame_6.setText(_translate("MainWindow", "Title"))
        self.Describtion_frame_6.setToolTip(_translate("MainWindow", "Description"))
        self.Describtion_frame_6.setText(_translate("MainWindow", "Description"))
        self.inputtime_frame_6.setToolTip(_translate("MainWindow", "Input Time"))
        self.inputtime_frame_6.setText(_translate("MainWindow", "Input time"))
        self.retime_frame_6.setToolTip(_translate("MainWindow", "Remaining Time"))
        self.retime_frame_6.setText(_translate("MainWindow", "00:00:00"))
        self.edit_btn_6.setToolTip(_translate("MainWindow", "Edit"))
        self.active_btn_6.setToolTip(_translate("MainWindow", "Active"))
        self.delete_btn_6.setToolTip(_translate("MainWindow", "Delete"))
        self.date_frame_6.setToolTip(_translate("MainWindow", "Date"))
        self.date_frame_6.setText(_translate("MainWindow", "date"))
        self.day_re_frame_6.setText(_translate("MainWindow", "days"))
        self.process_btn.setText(_translate("MainWindow", "  Process"))
        self.setting_btn.setText(_translate("MainWindow", "  Setting"))
        self.add_btn.setText(_translate("MainWindow", "Add Event"))
        self.refresh_btn.setText(_translate("MainWindow", "  Refresh"))
        self.menu_btn.setToolTip(_translate("MainWindow", "Menu"))
