# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 495)
        MainWindow.setMaximumSize(QtCore.QSize(491, 495))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #304352, stop:1 #d7d2cc);\n"
            "border-radius:5px;\n"
            "")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:none;\n"
                                 "border-Bottom:1px solid black;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(440, 10, 41, 21))
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_btn.setStyleSheet("background-color: rgb(255, 0, 0);\n"
                                    "border-radius:10px;")
        self.exit_btn.setText("")
        self.exit_btn.setObjectName("exit_btn")
        self.info_btn = QtWidgets.QPushButton(self.centralwidget)
        self.info_btn.setGeometry(QtCore.QRect(374, 90, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.info_btn.setFont(font)
        self.info_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.info_btn.setStyleSheet("QPushButton{\n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "    \n"
                                    "    background-color: rgb(115, 115, 115);\n"
                                    "border-radius:10px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "    background-color: rgb(95, 95, 95);\n"
                                    "border-radius:5px;\n"
                                    "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("photo/outline_info_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info_btn.setIcon(icon)
        self.info_btn.setIconSize(QtCore.QSize(32, 32))
        self.info_btn.setObjectName("info_btn")
        self.info_frame = QtWidgets.QFrame(self.centralwidget)
        self.info_frame.setGeometry(QtCore.QRect(20, 90, 341, 161))
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.label_2 = QtWidgets.QLabel(self.info_frame)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 271, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;")
        self.label_2.setObjectName("label_2")
        self.help_frame = QtWidgets.QFrame(self.centralwidget)
        self.help_frame.setGeometry(QtCore.QRect(20, 260, 341, 231))
        self.help_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.help_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.help_frame.setObjectName("help_frame")
        self.label_3 = QtWidgets.QLabel(self.help_frame)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 301, 191))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: none;")
        self.label_3.setObjectName("label_3")
        self.help_btn = QtWidgets.QPushButton(self.centralwidget)
        self.help_btn.setGeometry(QtCore.QRect(374, 160, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.help_btn.setFont(font)
        self.help_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help_btn.setStyleSheet("QPushButton{\n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "    \n"
                                    "    background-color: rgb(115, 115, 115);\n"
                                    "border-radius:10px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "    background-color: rgb(95, 95, 95);\n"
                                    "border-radius:5px;\n"
                                    "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("photo/outline_help_outline_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_btn.setIcon(icon1)
        self.help_btn.setIconSize(QtCore.QSize(32, 32))
        self.help_btn.setObjectName("help_btn")
        self.theme_btn = QtWidgets.QPushButton(self.centralwidget)
        self.theme_btn.setGeometry(QtCore.QRect(374, 228, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.theme_btn.setFont(font)
        self.theme_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme_btn.setStyleSheet("QPushButton{\n"
                                     "    color: rgb(255, 255, 255);\n"
                                     "    \n"
                                     "    background-color: rgb(115, 115, 115);\n"
                                     "border-radius:10px;\n"
                                     "}\n"
                                     "QPushButton:hover{\n"
                                     "    color: rgb(255, 255, 255);\n"
                                     "    background-color: rgb(95, 95, 95);\n"
                                     "border-radius:5px;\n"
                                     "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("photo/outline_brush_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.theme_btn.setIcon(icon2)
        self.theme_btn.setIconSize(QtCore.QSize(32, 32))
        self.theme_btn.setObjectName("theme_btn")
        self.theme_frame = QtWidgets.QFrame(self.centralwidget)
        self.theme_frame.setGeometry(QtCore.QRect(376, 290, 111, 201))
        self.theme_frame.setStyleSheet("background-color: none;")
        self.theme_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.theme_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.theme_frame.setObjectName("theme_frame")
        self.theme_2 = QtWidgets.QPushButton(self.theme_frame)
        self.theme_2.setGeometry(QtCore.QRect(10, 48, 91, 31))
        self.theme_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme_2.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #aa4b6b, stop:0.5 #6b6b83, stop:1 #3b8d99);")
        self.theme_2.setText("")
        self.theme_2.setObjectName("theme_2")
        self.theme_1 = QtWidgets.QPushButton(self.theme_frame)
        self.theme_1.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.theme_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme_1.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #304352, stop:1 #d7d2cc);\n"
            "border-radius:5px;\n"
            "")
        self.theme_1.setText("")
        self.theme_1.setObjectName("theme_1")
        self.theme_3 = QtWidgets.QPushButton(self.theme_frame)
        self.theme_3.setGeometry(QtCore.QRect(10, 88, 91, 31))
        self.theme_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme_3.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #654ea3, stop:1 #eaafc8); ")
        self.theme_3.setText("")
        self.theme_3.setObjectName("theme_3")
        self.theme_4 = QtWidgets.QPushButton(self.theme_frame)
        self.theme_4.setGeometry(QtCore.QRect(10, 127, 91, 31))
        self.theme_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme_4.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #8A2387, stop:0.5 #E94057, stop:1 #F27121);")
        self.theme_4.setText("")
        self.theme_4.setObjectName("theme_4")
        self.theme_5 = QtWidgets.QPushButton(self.theme_frame)
        self.theme_5.setGeometry(QtCore.QRect(10, 163, 91, 31))
        self.theme_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme_5.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #636363,stop:1 #a2ab58);")
        self.theme_5.setText("")
        self.theme_5.setObjectName("theme_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.exit_btn.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Setting Tab"))
        self.info_btn.setText(_translate("MainWindow", "  Info"))
        self.label_2.setText(_translate("MainWindow", "Powered by : Sajjad fani\n"
                                                      "Language : Python 3.9\n"
                                                      "Build date : 2021-10-05\n"
                                                      "ID Telegram : @sajad_fani"))
        self.label_3.setText(_translate("MainWindow", "1-At the first you should add event \n"
                                                      "or edit an event.\n"
                                                      "2-Please check , active button\n"
                                                      "should be green.\n"
                                                      "3-Click on Process button and wait\n"
                                                      "for notification.\n"
                                                      "Good luck ."))
        self.help_btn.setText(_translate("MainWindow", " Help"))
        self.theme_btn.setText(_translate("MainWindow", "Theme"))
        self.theme_2.setToolTip(_translate("MainWindow", "Theme 2"))
        self.theme_1.setToolTip(_translate("MainWindow", "Theme 1"))
        self.theme_3.setToolTip(_translate("MainWindow", "Theme 3"))
        self.theme_4.setToolTip(_translate("MainWindow", "Theme 4"))
        self.theme_5.setToolTip(_translate("MainWindow", "Theme 5"))
